// Prepares the in-browser demo: bundles the SQL migrations into a TS module and
// copies the PGlite (Postgres-in-WebAssembly) runtime files into public/pglite/.
// Runs automatically before `dev` and `build`.
import { copyFileSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const migDir = join(root, "supabase", "migrations");
const files = readdirSync(migDir).filter((f) => f.endsWith(".sql")).sort();
const body = files.map((f) => `  // ${f}\n  ${JSON.stringify(readFileSync(join(migDir, f), "utf8"))},`).join("\n");
writeFileSync(join(root, "src", "lib", "demo", "schema.generated.ts"),
  `// AUTO-GENERATED by scripts/build-demo.mjs from supabase/migrations — do not edit.\nexport const MIGRATIONS: string[] = [\n${body}\n];\n`);

const src = join(root, "node_modules", "@electric-sql", "pglite", "dist");
const out = join(root, "public", "pglite");
mkdirSync(out, { recursive: true });
for (const f of ["pglite.wasm", "pglite.data", "initdb.wasm"]) copyFileSync(join(src, f), join(out, f));
console.log(`demo: ${files.length} migrations bundled, PGlite runtime copied`);
