-- Official YES catalog, imported from the team's operating spreadsheet (Settings tab).
-- Prices in USD. Admin can edit everything from the Books page.
insert into public.books (code, name, category, unit_value, language, sort_order) values
  ('GDA', 'Guide des aliments (3 tomes)', 'Guides', 50.00, 'French', 1),
  ('GDP', 'Guide des plantes (2 tomes)', 'Guides', 35.00, 'French', 2),
  ('SPN', 'Santé par la nature (2 tomes)', 'Guides', 30.00, 'French', 3),
  ('RPG', '250 Recettes pour prevenir et guerir', 'New Lifestyle', 20.00, 'French', 4),
  ('RQC', '250 Recetas que curan', 'New Lifestyle', 20.00, 'Spanish', 5),
  ('RTH', '250 Recipes', 'New Lifestyle', 10.00, 'English', 6),
  ('DBT', 'Diabète', 'New Lifestyle', 8.00, 'French', 7),
  ('DAR', 'Disfrútalo (Ar)', 'New Lifestyle', 5.00, 'Arabic', 8),
  ('SPA', 'Santé par les aliments', 'New Lifestyle', 8.00, 'French', 9),
  ('SPAR', 'Santé par les aliments(Arabe)', 'New Lifestyle', 10.00, 'Arabic', 10),
  ('HFS', 'Healthy Foods', 'New Lifestyle', 10.00, 'English', 11),
  ('SPP', 'Santé par les plantes', 'New Lifestyle', 10.00, 'French', 12),
  ('EBSF', 'En bonne santé et forts', 'Life and Health', 13.00, 'French', 13),
  ('SYF', 'Sanos y Fuertes', 'Life and Health', 13.00, 'Spanish', 14),
  ('HAS', 'Healthy and Strong', 'Life and Health', 13.00, 'English', 15),
  ('LVPE', 'Le vrai pouvoir de L''Exercice Physique', 'Life and Health', 13.00, 'French', 16),
  ('PLE', 'Physical Exercise', 'Life and Health', 13.00, 'English', 17),
  ('EJF', 'Ejercicio Físico', 'Life and Health', 13.00, 'Spanish', 18),
  ('SPB', 'Santé par les boissons', 'Life and Health', 13.00, 'French', 19),
  ('HYJ', 'Healthy Juices', 'Life and Health', 13.00, 'English', 20),
  ('PMJ', 'Poder Medicinal de los jugos', 'Life and Health', 13.00, 'Spanish', 21),
  ('UCS', 'Un corps sain', 'Life and Health', 13.00, 'French', 22),
  ('HBY', 'Healthy Body', 'Life and Health', 13.00, 'English', 23),
  ('CPS', 'Cuerpo Saludable', 'Life and Health', 13.00, 'Spanish', 24),
  ('DAQ', 'Des Aliments Qui Guérissent', 'Magabooks', 10.00, 'French', 25),
  ('FTHAR', 'Food that Heals (Arabic)', 'Magabooks', 10.00, 'Arabic', 26),
  ('FTH', 'Food that Heals', 'Magabooks', 10.00, 'English', 27),
  ('AQC', 'Alimentos que curan', 'Magabooks', 10.00, 'Spanish', 28),
  ('DPQ', 'Des Plantes Qui Guérissent', 'Magabooks', 10.00, 'French', 29),
  ('PTH', 'Plants that Heal', 'Magabooks', 10.00, 'English', 30),
  ('PQC', 'Plantas que curan', 'Magabooks', 10.00, 'Spanish', 31),
  ('SWH', 'Sahtein w Hana', 'Magabooks', 10.00, 'Arabic', 32),
  ('HYP', 'Healthy Plate', 'Magabooks', 10.00, 'English', 33),
  ('NML', 'Nutrition Manual', 'Magabooks', 10.00, 'English', 34),
  ('URP', 'The Ultimate Recipe Book', 'Magabooks', 10.00, 'English', 35),
  ('ENR', 'Enchylopedia of Natural Remedies', 'Magabooks', 10.00, 'English', 36),
  ('EGS', 'Exercise Guidelines', 'Magabooks', 10.00, 'English', 37),
  ('HVS', 'Health and Vitality Secrets', 'Magabooks', 10.00, 'English', 38),
  ('SPLF', 'Straight Paths for Little Feet', 'Magabooks', 10.00, 'English', 39),
  ('HYK', 'Healthy Kids', 'Magabooks', 10.00, 'English', 40),
  ('RHS', 'Real Heroes', 'Magabooks', 10.00, 'English', 41),
  ('CFYB', 'Caring for your baby (Arabe)', 'Magabooks', 10.00, 'Arabic', 42),
  ('PATS', 'Peace Above the Storm', 'Magabooks', 10.00, 'English', 43),
  ('BAS', 'Bible Answers', 'Magabooks', 10.00, 'English', 44),
  ('ITB', 'In the beggining', 'Magabooks', 10.00, 'English', 45),
  ('TGH', 'The Great Hope', 'Magabooks', 10.00, 'English', 46),
  ('FAA', 'First Aid (Arabic)', 'Drop downs', 2.00, 'Arabic', 47),
  ('TPH', 'The Power of Hope', 'Drop downs', 1.00, 'English', 48),
  ('HAW', 'Health and Wellness', 'Drop downs', 1.00, 'English', 49),
  ('SDP', 'Signes D''spoir', 'Drop downs', 0.50, 'French', 50),
  ('GC', 'The Great Controversy', 'Drop downs', 2.00, 'English', 51),
  ('GCAR', 'The Great Controversy (Arabic)', 'Drop downs', 2.00, 'Arabic', 52),
  ('DOA', 'Desire of Ages', 'Drop downs', 2.00, 'English', 53),
  ('DOAR', 'Desire of Ages (Arabic)', 'Drop downs', 2.00, 'Arabic', 54),
  ('KTHAR', 'Keys to Happines (Arabic)', 'Drop downs', 0.50, 'Arabic', 55),
  ('CNS', 'Childen Stories', 'Drop downs', 2.00, 'English', 56),
  ('YHK', 'Youth Book', 'Drop downs', 2.00, 'English', 57),
  ('CEM', 'Concentration et Memoire', 'Drop downs', 2.00, 'French', 58),
  ('BIAR', 'Beyond Imagination (Arabic)', 'Drop downs', 1.00, 'Arabic', 59),
  ('LHL', 'Live Healthy Live Well', 'Tracks', 0.20, 'English', 60)
on conflict (code) do nothing;
